# Generated by Django 6.0.1 on 2026-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='time',
            field=models.TimeField(),
        ),
    ]
