# Generated by Django 6.0.1 on 2026-01-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_tournament_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='profile',
        ),
    ]
